### PR TITLE
Added qwik event

### PR DESCRIPTION
**Pull request by 404answernotfound**
Added SH Session event for Qwik Workshop

### CODE REVIEW

**Comment by TheJoin95** [comment]
It's looking good, we should add some description, you can take the one from eventbrite

I think we should add also a new section in the homepage, which is showing the upcoming events

**Review by davideimola — APPROVED** [review]
LGTM but as @TheJoin95 already said please add a few lines in the description!

**Comment by nicpuppa** [comment]
Remove visit website button

**Review by Wabri — APPROVED** [review]

**Comment by nicpuppa** [comment]
@404answernotfound can you also check this #82 ?

**Review by Wabri — CHANGES_REQUESTED** [review]
Broken visit website button
image

**Review by nicpuppa — APPROVED** [review]

**Review by Wabri — APPROVED** [review]
GG

+100 points to @Readpato

**Pull request merged**
