### PR TITLE
feat(community): add latina in tech

### PR DESCRIPTION
**Pull request by nicpuppa**
### 🔗 Linked issue

closes: #122 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Wabri — CHANGES_REQUESTED** [review]
the decription of the commit

**Comment by nicpuppa** [comment]
> the decription of the commit

keep calm bro

**Comment by Wabri** [comment]
> > the decription of the commit
> 
> keep calm bro

I will shutdown all the osday server if you merge a commit like that :see_no_evil:

**Review by TheJoin95 — APPROVED** [review]

**Comment by Wabri** [comment]
I dont need that

**Review by Wabri — APPROVED** [review]

**Pull request merged**
