### PR TITLE
Redesign team page - Closes #31

### LINKED ISSUE #31: Team Page restyling
The currently deployed team page has too much information, and continuously adding contributors may be a bit complicated to handle.

The proposal is to have a page like the following image. We can add an action with a link to open a modal with a full Bio and further information.

image

### PR DESCRIPTION
**Pull request by rennavittorio**
## Description
Close #31 

This PR is related to the [issue#31 - team page restyling](https://github.com/Schrodinger-Hat/schrodinger-hat-website/issues/31)

The restyle is based on a new grid-layout and the deletion of the description from the team-page.
Other features added:
- click on card to redirect into team-member detail page
- better contrast bg-color for light-mode team-page cards
- go back button on team-member page

## Changes

**What kind of change does this PR introduce?** (check at least one by adding an "x" between the brackets)

- [ ] Bugfix
- [ ] Feature
- [x] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Screenshots and videos**
new design
pr-issue-31-new-team-page-design

go back btn
pr-issue-31-member-go-back-button

ligth-mode card version
pr-issue-31-feedback-new-card-bg-color-ligth-v

**The PR fulfills these requirements:**

- [x] Schrödinger Hat [code of conduct](https://www.schrodinger-hat.it/code-of-conduct)

**Other information:**
e2e tests have been aligned and run, according to the team-page changes

### CODE REVIEW

**Review by AngyDev — APPROVED** [review]

**Review by Readpato — CHANGES_REQUESTED** [review]
Hey @rennavittorio! As I have already said, this is an awesome contribution. Thank you for doing this.
I would still ask for a small change. In the team page, the name of the team members are all an `<h1>` tag. For accessibility reasons, this shouldn't be like that, [there should only be one by page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page) you can also see the [WCAG standards](https://www.w3.org/WAI/tutorials/page-structure/headings/) regarding this issue. I would recommend to change them with an `<h2>` :)

I would also recommend to reduce the `font-size` of the `h2` to 28px and their `font-weight` to 400 or 500. Alternatively I would swap their weights so they are all pretty and lined up :)

**Comment by rennavittorio** [comment]
Hi @Readpato,
As anticipated, I've pushed the changes. Now:
- page title = h1, 32px (2rem), 700
- team-name = h2, 28px (1.75rem) 700

Here's a little preview of the page:
image

**Review by Readpato — APPROVED** [review]
Amazing, LGTM!

**Comment by Wabri** [comment]
AMAZING <3

**Pull request merged**
