### PR TITLE
feat(TheContributing): add nvimconf to partners

### LINKED ISSUE #105: [FEATURE]: new community sponsor Neovimconf
https://neovimconf.live/

### PR DESCRIPTION
**Pull request by Wabri**
### 🔗 Linked issue

close #105

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Add neovimconf.live to partners

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by TheJoin95** [comment]
Do we have their logo without the background? I'd prefer without background. Anyway it's not a blocker

**Review by TheJoin95 — APPROVED** [review]
Approved, let's wait for other feedbacks, maybe @Readpato and @nicpuppa

**Comment by Readpato** [comment]
I'll ask on the the nvim discord if they have te conference logo without a background, I would like it too without a bg

**Comment by nicpuppa** [comment]
Let's wait for a better logo

**Comment by Readpato** [comment]
I have already asked but got no answer, tomorrow I'll contact the admins of the conf directly!

**Comment by Wabri** [comment]
I've sent a message to adam, the admin of the nvimconf community. Let's wait!

**Comment by Wabri** [comment]
abd send me the minimal logo 👋  I'll update the PR later this day

**Comment by TheJoin95** [comment]
Did you update the PR?

**Comment by Wabri** [comment]
Sorry, I forgot to do it. I've done it now

**Pull request merged**
