### PR TITLE
header css bug fixed 

### LINKED ISSUE #27: Issue with header CSS
**on smaller screens <400px there seems to be an issue with CSS like this** 

Screenshot 2022-07-27 at 5 30 03 PM

### PR DESCRIPTION
**Pull request by sparsh-007**
closes #27

### CODE REVIEW

**Comment by TheJoin95** [comment]
Did you check also the :hover animation on the mobile website? Is it disabled now?

**Comment by sparsh-007** [comment]
> Did you check also the :hover animation on the mobile website? Is it disabled now? The`.title-part-1`and `.title-part-2`

okay that will have to disable for mobile i didn't touched the hover part in it

**Comment by sparsh-007** [comment]
> Did you check also the :hover animation on the mobile website? Is it disabled now? The`.title-part-1`and `.title-part-2`

i did not made any changes in the hover thing it is similar as before

**Comment by TheJoin95** [comment]
Ok, could you please disabled it on mobile then? thank you

**Comment by sparsh-007** [comment]
> Ok, could you please disabled it on mobile then? thank you

i have disabled the hover effect for mobiles and also corrected ImageNord as it should be coming in hamburger menu 
Screenshot 2022-07-28 at 9 18 13 PM

**Review by TheJoin95 — APPROVED** [review]
Great, thank you!

**Review by nicpuppa — APPROVED** [review]

**Pull request merged**
