### PR TITLE
Feature: Improve accessibility

### PR DESCRIPTION
**Pull request by MarcoJul**
# Improve website accessibility 

## Description

This is a Wip PR and refers to issue #70 - Improve accessibility

This PR contains the changes necessary to obtain the minimal accessibility requirements, such as:

- fix the descending order of the headings;
- addition of aria-label to all elements that concern the readability and interactivity of the page;
- addition of tab navigation to all text on pages, so it can be read by any screen reader;

The purpose of these changes is to make the entire website accessible via screenreaders and/or keyboard navigation.

## Changes

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [X] Other, please describe: add properties and minimal changes for accessibility purpose.

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [X] Schrödinger Hat [code of conduct](https://www.schrodinger-hat.it/code-of-conduct)

**Other information:**

- As a suggestion, until there is a multilanguage option and a language switcher, it might be better to change the lang tag in index.html to <html lang="it"> so that the screenreaders can work with the correct language.

### CODE REVIEW

**Comment by Readpato** [comment]
Hey @MarcoJul! First and foremost, thank you for this PR! It means a lot for us that people care about making Schrödinger Hat accessible and inclusive to all, so big love <3 <3

Being that said, lets make it even more so! Right now the `aria-text`s are not translated in both languages and that means i.e that when people see the page in Italian, they would see some `aria-text`s in English.

We can fix that by adding specific `aria-text`s to each element that you created. On the project under `src > i18n > messages.ts` you can find all the copy that we utilize in this project which leverages [VueI18n](https://vue-i18n.intlify.dev/) to add text based on its internal `locale` variable (which as of now it's assigned automatically via browser detection) and then we utilize the `$t()` or `t()` methods to display the correct text. 
I would recommend adding a value for each `aria-text` that has been created in both languages so we can handle either English and Italian cases.

If something isn't clear let me know, more than glad to give you a hand!

**Review by Readpato — CHANGES_REQUESTED** [review]
Hey @MarcoJul! First and foremost, thank you for this PR! It means a lot for us that people care about making Schrödinger Hat accessible and inclusive to all, so big love <3 <3

Being that said, lets make it even more so! Right now the `aria-text`s are not translated in both languages and that means i.e that when people see the page in Italian, they would see some `aria-text`s in English.

We can fix that by adding specific `aria-text`s to each element that you created. On the project under `src > i18n > messages.ts` you can find all the copy that we utilize in this project which leverages [VueI18n](https://vue-i18n.intlify.dev/) to add text based on its internal `locale` variable (which as of now it's assigned automatically via browser detection) and then we utilize the `$t()` or `t()` methods to display the correct text. 
I would recommend adding a value for each `aria-text` that has been created in both languages so we can handle either English and Italian cases.

If something isn't clear let me know, more than glad to give you a hand!

**Comment by MarcoJul** [comment]
Hi @Readpato! You're absolutely right, the translation of these strings is missing! I'll add it for every aria-text and then add new commits!

If I face any difficulties, I'll ask you for information!

Thank you again😉

**Comment by MarcoJul** [comment]
Hi @Readpato, I just have a question about integrating translations in messages.ts:
```
main: {
      h1: 'Schrödinger Hat',
      h2: 'The Open Source community',
      links: {
        youtube: 'YouTube',
        spotify: 'Spotify',
        openCollective: 'OpenCollective',
      },
    },
    contributing: {
      'title': 'Contribute',
      'is-a-project': 'is an open source project on',
      'cta': 'If you have an idea, a tool, a topic or something else to propose, you can',
      'cta-2': 'Or you can contact us via social networks.',
      'external-link': 'open a GitHub issue',
    },
```

There are some object with keys as string and some not. How should I add my new key-value to the translations? Is there some meaning I am missing? 

Thank you for your help!

**Comment by Readpato** [comment]
Hey @MarcoJul! You can proceed to add them as you see fit being either an object or a single string. If I can give you my advice, you could create a property called `accessibility` in each language key ( `en` and `it`) on the `messages` object and then I would proceed to subdivide from there. You can either proceed by dividing them in the pages sections and more general things =]

As an example:

```
// messages.ts

const messages = {
  it: {
    accessibility: {
      contributing: {
        discord: 'Join our discord',
        // ...
      },
      // ...
    },
  },
  en: {
    accessibility: {
      contributing: {
        discord: 'Unisicit al nostro discord',
        // ...
      },
    },
  },
}
```

**Comment by MarcoJul** [comment]
Hi @Readpato, 

I will proceed as you suggest, in fact I was thinking of maintaining some sort of separation in this object, in order to keep every future insert simple and clean ;)

Thank you!🙌

**Comment by MarcoJul** [comment]
Hi @Readpato, 

I added all the aria labels to the translations file and did another general check of the entire website.
Everything seems fine, at least for a first improvement, except this error:

image

This is related to the recent addition of the EmailOctopus script, and fires whenever you press the tab key while browsing the website.

It doesn't seems to cause any problems, but I can't really figure out how to handle it.

Let me know and thank you for the review!

**Comment by Readpato** [comment]
Hey @MarcoJul! Sorry for the force push on the history, I committed the fix for the error with another account and had to remove it 😓 

Being that said, this one was a tricky one. The `<script>` tag injected from EmailOctopus isn't the greatest, because they where adding an `eventListener` of type `keydown` with a callback which after some conditionals it focused on an element of the form. Once the form has been dismissed for the first time, this element would never appear again...

```js
const onKeyDown = event => {
    setTimeout(function () {
        // If we tab past the focusable elements in the modal,
        // bring the focus back to the first focusable element.
        if (
            event.key === 'Tab' &&
            !formWrapper.contains(document.activeElement)
        ) {
            formWrapper.querySelector('[tabindex="1"]').focus(); // Error here: Cannot read properties of null (reading 'focus')
        }
    }, 0);

    if (event.key === 'Escape' || event.key === 'Esc') {
        hideForm(formWrapper);
    }
};
```

You can see the whole script for yourself if you go to (using chrome):
`DevTools > Sources > Page (on the upper right) > top > eocampaign1.com > form > e9fb[...].js`

The workaround that I found was creating a composable called `useNewsletter` which would create the Octopus `<script>` and add it to the head of the page if the newsletter cookie hasn't been already registered in the app. This composable will be executed with the `onMounted` callback from Vue and in this way we wont have an useless `eventListener` hanging from the document. 

If you want to test it out, you can go to `DevTools > Application > Storage > Cookies > [url]` and you can delete the `eoForm` cookie =]

The only bad thing about this which we can't do something about is that when the cookie is not detected and the newsletter hasn't appeared yet, the `<script>` will be created and there will be a period of time where the error will appear if any key is pressed (not only tab). Sadly we can't do much more because we can't remove an `eventListener` because it being "anonymous"  we can't find it and  remove it with a `removeEventListener`

Besides that, I have made a review to everything else and it looks amazing, thank you so much for your contribution :heart:

Let me know if the solution of the error works for you and if it does we could proceed with the merging of this PR!

**Review by Readpato — APPROVED** [review]

**Comment by Readpato** [comment]
@MarcoJul everything seems ok to me! Proceeding with the merge =]

**Pull request merged**
