### PR TITLE
Feature/volta nvm setup

### LINKED ISSUE #3: Enforcing the node version
We want to introduce some sort of enforcement for the Node version.

We can set this thing by using:

- package.json node and npm engine versions
- a `.nvmrc` file for nvm users
- configuring volta in the repository

Probably I will go with setting all these three enforcement, but I am open to other ideas!

@gianfabiopezzolla @Wabri @404answernotfound @TheJoin95  what are your thoughts?

### PR DESCRIPTION
**Pull request by gianfabiopezzolla**
Hi there,

I've implemented volta + nvm.

I have also added a .npmrc file which strict the node version of the current project; in this way if someone try to install some packages with another node version will raise an error.

closes #3

### CODE REVIEW

**Comment by Wabri** [comment]
The build failed because of this error **Failed to install node version '14.0.26' ** maybe the problem comes from package.json

**Review by davideimola — COMMENTED** [review]
I think we must add this thing to the package.json too

```
"engines" : { 
    "node": "12.22.10",
    "npm": "6.14.12"
  **}**
```

**Comment by gianfabiopezzolla** [comment]
> "engines" : { 
>     "node": "12.22.10",
>     "npm": "6.14.12"
>   **}

Property added in last commit: 059db441e0d3080960e2ff709a749c9408af575b

**Review by davideimola — APPROVED** [review]
LGTM

**Review by Wabri — APPROVED** [review]
GG

**Pull request merged**
