### PR TITLE
feat: add logo italia opensource

### PR DESCRIPTION
**Pull request by FabrizioCafolla**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Add logo Italia Open-Source community for partnership.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nicpuppa** [comment]
Hey @FabrizioCafolla thanks for your contribution. I don't understand what this PR should do, can you clarify ? 

Are you working on #124 ? If yes please link the issue in the description. Also you should update [this lines](https://github.com/Schrodinger-Hat/schrodinger-hat-website/blob/66ecc99049cf86d39ba9475273a65eb0f711e761/src/components/TheContributing.vue#L117-L119) by adding your community.

Thank you 😄

**Comment by FabrizioCafolla** [comment]
@nicpuppa Hi, yes certainly
Yesterday I was notified by events@schrodinger-hat.it (following a call a few weeks ago) that the partnership had been approved and that I could put the logo in this repository and in osday.

**Review by Wabri — CHANGES_REQUESTED** [review]
Need to add new entry here https://github.com/Schrodinger-Hat/schrodinger-hat-website/blob/66ecc99049cf86d39ba9475273a65eb0f711e761/src/components/TheContributing.vue#L120

**Review by Wabri — APPROVED** [review]
LGTM

**Pull request merged**
