### PR TITLE
Migrate project to Vue3

### LINKED ISSUE #42: [FEATURE]: Update Vue2 to Vue3
## Feature request

This issue aims to propose the update of the Vue version used in this project (v2.6.14), to its newest version [Vue3](https://vuejs.org/).

### Why is it needed?

The main reason for this feature is because Vue2 will enter [EOL in December 2023](https://v2.vuejs.org/lts/). Which means it will no longer receive updates, including security and browser compatibility fixes.
 
### What will improve?
 
 This feature will allow us to utilize all the new features that come integrated with Vue 3, such as:

- [Composition API](https://vuejs.org/guide/extras/composition-api-faq.html) to point out a few advantages: greatly improves the DX, introduces the [<script setup>](https://vuejs.org/api/sfc-script-setup.html#script-setup) syntax sugar, [offers a smaller production bundle](https://vuejs.org/guide/extras/composition-api-faq.html#smaller-production-bundle-and-less-overhead), etc.

- First class [Typescript support](https://vuejs.org/guide/typescript/overview.html#using-vue-with-typescript) as it was written completely in [Typescript](https://www.typescriptlang.org/). This also offers a good [Typescript experience with the Composition API](https://vuejs.org/guide/typescript/composition-api.html).

Migrating to Vue3 will also allow us to utilize different libraries that have been created and/or improved this past years and at the same time, to stay up to date to any new changes in the web development world. To name a few examples:

- [Vite](https://vitejs.dev/) which is super fast when building and also while working on development mode.
- [Vitest](https://vitest.dev/) which is native to Vite and allows us to create faster and easier unit tests, [more info](https://vitest.dev/guide/why.html).
- [Cypress v12](https://docs.cypress.io/guides/overview/why-cypress#Cypress-ecosystem) which allows us to write more robust E2E tests.
- [Vue i18n v9](https://vue-i18n.intlify.dev/) which includes [new features](https://vue-i18n.intlify.dev/guide/migration/features.html) that could be implemented along with Vue3.

### How will this be achieved?

I think the best way to implement this feature will be to follow the [official Vue3 migration guide](https://v3-migration.vuejs.org/), which provides a thorough explanation on how to correctly migrate an app from Vue2 to Vue3. 

For further assistance, there is additional content that could ease and help the transition between versions.

- [Alex Van Liew presents “How we migrated our HUGE app to Vue 3” at VueConf US 2022](https://youtu.be/lPfp9XZINrg). This talk also answers a critical question "Why migrate now (or at all)?"
- [Marina Mosti - Migrating Vue 2 to Vue 3 - Vuejs Amsterdam 2021](https://youtu.be/9Eh5bMX_lqM)
- [Daniel Kelly: How to Migrate from Vue CLI to Vite – vuejs.de Conf 2022](https://youtu.be/PAT7SbdTBjI)

**Additional content/notes**

I think the transition from Vue2 to Vue3 is a step forward for this project. Not only will it allow us to keep updated with the latest Vue ecosystem updates, it will also allow new developers that are learning Vue or are searching a nice Open Source project to contribute to, to easily get onboard and start contributing.

### LINKED ISSUE #52: [FEATURE]: Add VueUse as a dependency
**Describe the new content**

Add [VueUse](https://vueuse.org/) as a dependency for this project to utilize with Vue3.
Improves #49 

- Why is it needed?
VueUse is a library that offers many utility functions that can be implemented into this project to provide new features which are easy to utilize as well (See: [All VueUse functions](https://vueuse.org/functions.html))

**Your example on how the new content would be like**
Right now on our new Vue3 component, `TheNavbar`, we have this code that allows us to know if an user has activated the dark mode and the possibility to toggle it.

```js
onMounted(() => {
  if (localStorage.getItem('darkMode') === 'yes')
    document.querySelector('.dark-mode-icon').parentNode.click()
})

const toggleDarkMode = () => {
  event.preventDefault()
  document.body.parentNode.classList.toggle('dark-theme')
  let iconElement = event.target
  iconElement = iconElement.tagName === 'A' ? iconElement.children[0] : iconElement

  let darkModeValue = 'yes'
  darkModeValue
    = localStorage.getItem('darkMode') === 'yes' && iconElement.className.includes('fa-sun')
      ? 'no'
      : 'yes'

  iconElement.classList.toggle('fa-moon')
  iconElement.classList.toggle('fa-sun')

  localStorage.setItem('darkMode', darkModeValue)
}
```

This whole chunk of code could be replaced with two VueUse functions as following:

```js
import { useDark, useToggle } from '@vueuse/core'

const isDark = useDark()
const toggleDark = useToggle(isDark)
```

> Note: On the VueUse example it would be needed one more extra line that manages the icon toggling for dark mode.  

For example and totally hypothetically, we could add some animation to our team members cards and our events with four lines of codes utilizing the `useParallax` function. (See: [useParallax](https://vueuse.org/core/useParallax/))

> Note: On the example above, the `script setup` syntax it's not being used, so it would be even less lines of code on our project, for a total of 4 :)

**If needed, include anything else that would help to solidify the new proposed changes**
I have made a list of pros and cons of adding VueUse to the project:

Pros:
- Works with both Vue2 and Vue3
- Fully written in Typescript 
- Tree shakeable
- Has a lot of functions that can be implemented

Cons:
- Adding a new dependency to the project (Which is not that [heavy](https://bundlephobia.com/package/@vueuse/core@9.12.0) though)

Let me know what you think and also if this is a good step forward for this project!

### PR DESCRIPTION
**Pull request by Readpato**
**Summary**
This project aims to migrate to Vue3 and update all its dependencies needed for this change.

Resolves #42
Resolves #52

## Changes

- [ ] Bugfix
- [x] Feature
- [x] Code style update
- [x] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

- The migration path taken is followed from [Vue 3 Migration Guide](https://v3-migration.vuejs.org/)

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature: [[FEATURE]: Update Vue2 to Vue3](https://github.com/Schrodinger-Hat/schrodinger-hat-website/issues/42)

**Checklist for migration**
- [x] Migrate from Vue CLI to Vite
- [x] Update Vue2 to Vue3 
- [x] Update Vue router from v3 to v4
- [x] Update Vue i18n from v8 to v9
- [x] Add Typescript as a dependency
- [x] Add VueUse as a dependency
- [x] Update Cypress to it's latest version
- [X] Add Vitest as a dependency
- [x] Refactor components to utilize Typescript and Vue3 features
- [x] Refactor views to utilize Typescript and Vue3 features
- [x] Create E2E tests with Cypress
- [ ] Create unit tests with Vitest
- [x] Remove unnecessary dependencies
- [x] Restore files needed for deployment

**The PR fulfills these requirements:**

- [x] Schrödinger Hat [code of conduct](https://www.schrodinger-hat.it/code-of-conduct)

### CODE REVIEW

**Review by nicpuppa — APPROVED** [review]

**Comment by nicpuppa** [comment]
Well done Pat 🔥

**Review by TheJoin95 — APPROVED** [review]
You are my hero.

Could you update the readme.md and add the useful commands to run in dev, build in prod, run test etc?

**Comment by Readpato** [comment]
> You are my hero.
> 
> Could you update the readme.md and add the useful commands to run in dev, build in prod, run test etc?

Yes, that's the first thing to do after the merging is complete as it's the most urgent one :)

**Comment by davideimola** [comment]
@Readpato I'll suggest to update the README directly inside of this PR 😄

**Review by 404answernotfound — APPROVED** [review]

**Review by AngyDev — APPROVED** [review]

**Review by davideimola — APPROVED** [review]

**Review by Wabri — APPROVED** [review]

**Pull request merged**
